### PR TITLE
Switched from 'AzureAD' to 'Az' Module

### LINKED ISSUE #10: get-graphTokenForIntune : Failed to retrieve access token from Azure
Receiving following error on global admin without MFA

get-graphTokenForIntune : Failed to retrieve access token from Azure
At line:954 char:21
+ ... l:authToken = get-graphTokenForIntune -User $user -Password $password
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,get-graphTokenForIntune
 
get-graphTokenForIntune : access token is null!
At line:954 char:21
+ ... l:authToken = get-graphTokenForIntune -User $user -Password $password
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,get-graphTokenForIntune

### PR DESCRIPTION
**Pull request by RobinBeismann**
Switched all requirements from AzureAD to Az module as this fixes #10 and makes the script work out of the box again.

### CODE REVIEW

**Comment by ThomasKur** [comment]
Has that really worked on your side? I tried it in a new PowerShell session, but still got errors?

**Comment by RobinBeismann** [comment]
It did last time, however I've just tried it on a fresh machine and it failed like yours. Looks like I had another module loaded when I created the commit.
I'll fix it and push another commit - sorry.

**Comment by RobinBeismann** [comment]
I've fixed the issue, looks like the AzureRM Modules were merged into the Module Suite "Az", which also changes the Token Aquisition as the API doesn't return a refresh token anymore.
My VSCode extensions autoformatted the code, sorry for that many changes.

Here's a post about the changes on the token aquisition workflow: https://github.com/Azure/azure-powershell/issues/7525

**Comment by ThomasKur** [comment]
Hi Robin,
I have completely rewritten the script to use the new Intune PowerShell Module. So all the MFA Stuff is now working without a problem. I just did the changes in a new file. Please check it out. Also extended with some additional information.

**Pull request closed without merging**
